### ISSUE TITLE
Object annotations in ASRL

### ISSUE THREAD

**Issue by forence** [TheShadow29/vognet-pytorch#2]
Hi Arka,

Thanks for your great job!

I noticed that there was only one object annotation for each noun phrase in a specific frame in ActivityNet-Entities. Did you annotate objects bbx in all key frames for each entities?  If so, how could you guarantee that the bbx other than  ActivityNet-Entities‘ are accurate?

Best Regards

**Comment by TheShadow29** [comment]
Hi @forence 

Yes, AE only provides one bounding box for a noun-phrase across 10 frames.

So we consider prediction only in the annotated frame. In Single Video case (SVSQ), we don't consider the other frames. However, for spatial and temporal concatenation cases, we know objects appearing in other frames are incorrect, so if any such object is predicted with probability greater than some threshold, we consider it incorrect.

Section 4.3 and Appendix C of the paper clarifies this in more detail.

Does that answer your question?
