### ISSUE TITLE
About Training

### ISSUE THREAD

**Issue by AmingWu** [TheShadow29/vognet-pytorch#4]
Dear Authors,

Now I am running your code. I find the training process is very slow. Each epoch takes around 6 hours. The used GPU is 1080ti. The GPU memory of your code is around 2GB. Could you give me some advice? Thank you very much.

**Comment by TheShadow29** [comment]
@AmingWu Is it possible that your features are stored in HDD? It is recommended to store it in SSD. I too faced a similar problem, and it is noted in the [readme file](https://github.com/TheShadow29/vognet-pytorch/tree/master/data#quickstart). 

The gpu part seems correct (assuming you are using GT5 setting).

**Comment by TheShadow29** [comment]
I am closing this issue, feel free to re-open or create a new issue in case of any queries.
