### ISSUE TITLE
Inference on a single video

### ISSUE THREAD

**Issue by nikky4D** [TheShadow29/vognet-pytorch#5]
Hi,

I would like to run vognet on a single video input for inference. Is there an example code that works for a single video/folder of videos? for instance, what code to get the features from a single video, then run inference on the features to get final captions

thanks

**Comment by TheShadow29** [comment]
@nikky4D thank you for your interest.

Getting it to work with single videos is a bit tricky. You would need to use the same feature extraction pipeline as used in (https://github.com/facebookresearch/grounded-video-description). 

The steps would be (also see https://github.com/facebookresearch/grounded-video-description/issues/12):
1. Extract Video Frames (using say FFmpeg)
2. Extract video features (both rgb and flow features) to get `rgb_motion_1d`
3. Sample 10 frames for each video clip, and pass them through object detector like faster-rcnn trained on visual genome `fc6_feat_100rois` (the directory contains features) and `anet_detection_vg_fc6_feat_100rois.h5` (the h5 file contains the bounding box proposals)

For (2), see https://github.com/LuoweiZhou/anet2016-cuhk-feature and for (3), see https://github.com/facebookresearch/grounded-video-description/issues/5

For this project (and paper), we used the extracted features directly (which can be downloaded). 
At the moment, there are no plans to reproduce the whole pipeline, but pull requests are more than welcome!

**Comment by nikky4D** [comment]
I actually have the 1) and 3) done. The author of VLP was very helpful in sorting out those issues for me. I only have 2 left and I believe I can figure out 2 quickly. 

After that, what do I use as input commands? For example, I already have the fc6_feat_100rois, and the anet_detection_vg_fc6...f features. Once I have the rgb_motion_1d, what is the next step for generating captions without running evaluations on the results? Would it be the same as: 

`python code/main_dist.py "spat_vog_gt5_valid" --train.resume=True --train.resume_path='./tmp/models/spat_vog_gt5.pth' --mdl.name='vog' --mdl.obj_tx.use_rel=True --mdl.mul_tx.use_rel=True --only_val=True --train.prob_thresh=0.2`

Also, do I need to have rgb_motion_1d (just in case I don't get it working)? 

Thanks

**Comment by TheShadow29** [comment]
@nikky4D I am not sure if I follow, "what is the next step for generating captions without running evaluations on the results"

Note that the task here is to ground objects using a given query, so the captions should already be provided (there is no caption generation step). Given captions for video segments, they are passed through a semantic role labeling system, which is further used for contrastive sampling.

It is great that you have 1,3 done. While you could skip 2, you wouldn't be able to use the pre-trained models. So you would need to re-train the models by removing the temporal features. It would need some changes to the code as well, basically, you would need to comment out the concatenation of proposal features and segment features (https://github.com/TheShadow29/vognet-pytorch/blob/master/code/mdl_conc_single.py#L100).

**Comment by nikky4D** [comment]
Thanks @TheShadow29 . I do have sample videos with their initial captions.  I also have video features (1, and 3). I will also get video features (2) soon. 

My issue is really stupid. I'm trying to figure out the input commands for generating model predictions/inference and where to store my own videos, captions and features. 

So,  using the pretrained model checkpoints, and with my video features, what is the code to get out model predictions? I am assuming it is something like the 2 stage process described in readme: 
1. Get the valid_0.pkl files
`python code/main_dist.py "spat_vog_gt5_valid" --train.resume=True --train.resume_path='./tmp/models/spat_vog_gt5.pth' --mdl.name='vog' --mdl.obj_tx.use_rel=True --mdl.mul_tx.use_rel=True --only_val=True --train.prob_thresh=0.2`

2. Evaluate the pkl files
`python code/eval_fn_corr.py --pred_file='./tmp/predictions/spat_vog_gt5_valid/valid_0.pkl' --split_type='valid' --train.prob_thresh=0.2`

But where do I describe the path to my own videos, captions, and features so that I can evaluate the model on them? 

I hope this makes more sense.

**Comment by TheShadow29** [comment]
@nikky4D All paths are defined in config.yml files (https://github.com/TheShadow29/vognet-pytorch/blob/master/configs/anet_srl_cfg.yml)

The easiest way would be to simply create symlinks though. So you could create `data` and provide a symlink to `anet/rgb_motion1d` in data.

Alternatively, you could pass them as arguments as well which would look like: 
```
python code/main_dist.py "spat_vog_gt5_valid" --train.resume=True \
 --train.resume_path='./tmp/models/spat_vog_gt5.pth' --mdl.name='vog' \
--mdl.obj_tx.use_rel=True --mdl.mul_tx.use_rel=True --only_val=True --train.prob_thresh=0.2 \
--ds.seg_feature_root=/path/to/segfeat
```

Does that make sense?

**Comment by nikky4D** [comment]
That does. Thank you very much. I'll get to work on that.
