### ISSUE TITLE
How to train the model on other dataset?

### ISSUE THREAD

**Issue by mzshuo** [TheShadow29/vognet-pytorch#6]
Hi,

Thank you for your great job. I'd like to know if I want to train the model on my own dataset containing video-sentence pairs with bounding box annotations, what should I do? Should I replace the ASRL dataset with my own dataset directly, and extract features manually, or replace ActivityNet-Entity and ActivityNet-Caption dataset separately and apply your 'dcode' files to process them? 

Furthermore, if I don't want to use "contrastive sample" during training(because my dataset has already have multiple objects for a phrase), then what changes should I make to the model?

Thanks in advance.

**Comment by TheShadow29** [comment]
@shuorr Great Question!

The model is handled separately from the data. So you can directly follow the steps for `svsq` which is a single video single query model. This will turn off contrastive sampling. You might have to add a dimension for handling multiple queries for the same video via some `tensor.expand` operation though.

You can find the instructions to run `svsq` models at `EXPTS.md`

To set up the dataset part, it is best if you handle it separately. Currently, `dcode` doesn't completely support feature extraction. You need visual features + object features via some third-party code (like slowfast network and faster-rcnn on visual genome) preferably extracted in `ssd` and read them in your `Dataset` reader part. 

Let me know if that answers your question. Happy to help.

**Comment by mzshuo** [comment]
@TheShadow29 

Thank you so much for your reply. It's very clear, I got it and am trying to follow your instruction to deal with my dataset. 

There is another problem now. For `SPAT` strategy the videos need to be sampled 10 frames per video to align, but how about other strategies like `svsq`? Can I directly use all frames(about 500 frames per video) or downsampled 100 frames to extract features? Does that have explicit impact on the speed of training? But just using 10 frames per video seems not reasonable for my situation(each video  segment spans up to 20 seconds).

Thanks a lot.

**Comment by TheShadow29** [comment]
@shuorr I believe it should be straightforward, just need to change `num_sampled_frm` to be your desired number in `anet_srl_cfg.yml`. The code would sample these many frames from the entire sequence.

**Comment by mzshuo** [comment]
OK. Thank you!
