### ISSUE TITLE
Annotations for (begin_frame, end_frame)?

### ISSUE THREAD

**Issue by JackyWang2001** [TheShadow29/vognet-pytorch#7]
Hi, Arka. Thanks for your work.
I am interested in using this dataset for temporal grounding. However, I think I get some misconceptions about the annotations of gt_frms. I am wondering how should I differentiate the frame_begin and frame_end in order to find the gt segment?
Thank you!

**Comment by TheShadow29** [comment]
@JackyWang2001 Thanks for your interest. 

I am not sure if I understand your question well. Could you perhaps give an example of what your task is?

**Comment by JackyWang2001** [comment]
@TheShadow29 
Sorry for the misleading wording. For temporal grounding, we want to locate the time interval when the language query of the action corresponds to (without the locating objects, so it is an easier task of video grounding). But I am wondering how can we get (frame_begin, frame_end)?

**Comment by TheShadow29** [comment]
@JackyWang2001  

So in this work we only work on spatial localization within a trimmed video. If you want temoral grounding, you could use the untrimmed video from activity net instead. ActivityNet-Captions would have the start-end times for the same. 

You could also look at other datasets such as Charades-STA or DiDeMo if you are particularly interested in temporal grounding. 

Let me know if that answers your question.

**Comment by JackyWang2001** [comment]
Thank you for your replies and suggestions. That makes much sense.
